scripts: improve build-amis

diff --git a/scripts/build-amis b/scripts/build-amis
--- a/scripts/build-amis
+++ b/scripts/build-amis
@@ -5,6 +5,21 @@ set -euo pipefail
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly SCRIPT_NAME="$(basename "$0")"
 
+function print_usage {
+  echo
+  echo "Usage: $SCRIPT_NAME [OPTIONS]"
+  echo
+  echo "This script is used to build all the AMIs used by the Nomad stack."
+  echo
+  echo "Options:"
+  echo
+  echo -e "  --region\t\tThe AWS region to build the AMIs in.  Defaults to eu-west-1."
+  echo
+  echo "Examples:"
+  echo
+  echo "  $SCRIPT_NAME --region eu-east-1"
+}
+
 log() {
 
   local readonly level="$1"
@@ -12,6 +27,17 @@ log() {
   local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
 
   >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+}
+
+assert_not_empty() {
+  local -r arg_name="$1"
+  local -r arg_value="$2"
+
+  if [[ -z "$arg_value" ]]; then
+    log "ERROR" "The value for '$arg_name' cannot be empty"
+    print_usage
+    exit 1
+  fi
 }
 
 assert_is_installed() {
@@ -33,6 +59,7 @@ assert_exists() {
 }
 
 build_amis() {
+  local -r region="$1"
 
   local -r ami_dir="$SCRIPT_DIR/../amis"
 
@@ -40,9 +67,13 @@ build_amis() {
   for path in "$ami_dir"/*/*.json; do
 
     pushd "$(dirname "$path")" &> /dev/null
-      log "INFO" "Building $(basename "$path") AMI"
+      local filename=$(basename "$path")
 
-      packer build "$(basename "$path")"
+      log "INFO" "Building $filename AMI"
+
+      packer build \
+        -var "region=$region" \
+        "$filename"
 
     popd &> /dev/null
 
@@ -51,6 +82,30 @@ build_amis() {
 }
 
 run() {
+  local region="eu-west-1"
+
+  while [[ $# -gt 0 ]]; do
+    local key="$1"
+
+    case "$key" in
+      --region)
+        assert_not_empty "$key" "$2"
+        region="$2"
+        shift
+        ;;
+      --help)
+        print_usage
+        exit
+        ;;
+      *)
+        log "ERROR" "Unrecognized argument: $key"
+        print_usage
+        exit 1
+        ;;
+    esac
+
+    shift
+  done
 
   assert_is_installed "packer"
 
@@ -58,7 +113,11 @@ run() {
   assert_exists "$SCRIPT_DIR/../configuration/tls/localhost.crt"
   assert_exists "$SCRIPT_DIR/../configuration/tls/localhost.key"
 
-  build_amis
+  log "INFO" "Building AMIs in $region..."
+
+  build_amis "$region"
+
+  log "INFO" "Done.  All AMIs built"
 }
 
 run "$@"
